# This is a basic workflow to help you get started with Actions

name: Test

on:
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build distribution
        id: build
        run: |
          echo "${{ secrets.FIGMA_TOKEN }}" > figex-cli/.figmatoken
          gradle clean check -PAzureBuildNumber="${{ github.run_id }}"

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/linux@v2
        if: always()
        with:
          files: |
            gradle-plugin/build/test-results/**/*.xml

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Test Results
          path: gradle-plugin/build/reports/**